### ISSUE TITLE
Higher half

### ISSUE THREAD

**Issue by Senc3951** [LensPlaysGames/LensorOS#9]
Hi, maybe I'm just blind but I saw that the kernel is loaded into the higher half in memory but I couldn't see a place that actually maps the kernel into that part, so the bootloader just assumes that the kernel is mapped there

**Comment by LensPlaysGames** [comment]
you are blind

https://github.com/LensPlaysGames/LensorOS/blob/5bf12424bb938274a46142ba0e79205b9bd8560a/kernel/kernel.ld

**Comment by Senc3951** [comment]
I am aware of the linker, but also, the bootloader should map the kernel into the higher half of memory which I can't see where it is done

**Comment by LensPlaysGames** [comment]
1. Issues aren't handled here. If you read the first line of the readme you'd know that.

2. The bootloader doesn't need to because the prekernel does.

3. Don't make another issue just to ask a question about if there is an issue. The entire thing wouldn't work if the kernel was never mapped, so try thinking critically for two seconds.

4. You're annoying
